engines:
  phpcodesniffer:
    enabled: true
    checks:
      Generic WhiteSpace DisallowTabIndent TabsUsed:
        enabled: false
      PSR1 Files SideEffects FoundWithSymbols:
        enabled: false
      Squiz WhiteSpace ControlStructureSpacing SpacingAfterOpen:
        enabled: false
      Generic WhiteSpace DisallowTabIndent NonIndentTabsUsed:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - php
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false
  phan:
    enabled: true
    config:
      file_extensions: "php"

ratings:
  paths:
  - "**.php"


exclude_paths:
- helper/**/*
- js/**/*
- PHPExcel/**/*
- tests/**/*