engines:
  phpcodesniffer:
    enabled: true
    checks:
      Generic WhiteSpace DisallowTabIndent TabsUsed:
        enabled: false
      PSR1 Files SideEffects FoundWithSymbols:
        enabled: false
      Squiz WhiteSpace ControlStructureSpacing SpacingAfterOpen:
        enabled: false
      Generic WhiteSpace DisallowTabIndent NonIndentTabsUsed:
        enabled: false
      Generic Formatting DisallowMultipleStatements SameLine:
        enabled: false
      Generic PHP LowerCaseConstant Found:
        enabled: false
      Squiz WhiteSpace ControlStructureSpacing SpacingBeforeClose:
        enabled: false
      Generic PHP LowerCaseKeyword Found:
        enabled: false
      Generic Files LineLength TooLong:
        enabled: false
      Generic ControlStructures InlineControlStructure NotAllowed:
        enabled: false
      Generic WhiteSpace ScopeIndent IncorrectExact:
        enabled: false
      Squiz ControlStructures ControlSignature SpaceAfterKeyword:
        enabled: false
      Squiz ControlStructures ControlSignature SpaceAfterKeyword:
        enabled: false
      Squiz ControlStructures ControlSignature SpaceAfterCloseParenthesis:
        enabled: false
      PSR2 ControlStructures SwitchDeclaration BreakIndent:
        enabled: false
      Squiz WhiteSpace ScopeClosingBrace Indent:
        enabled: false
      Squiz WhiteSpace SuperfluousWhitespace EndLine:
        enabled: false
      Squiz ControlStructures ControlSignature SpaceAfterCloseBrace:
        enabled: false
      PSR2 Files ClosingTag NotAllowed:
        enabled: false
      Squiz ControlStructures ControlSignature NewlineAfterOpenBrace:
        enabled: false
      PSR2 Files EndFileNewline NoneFound:
        enabled: false
      Squiz WhiteSpace ScopeClosingBrace ContentBefore:
        enabled: false
      Generic Functions FunctionCallArgumentSpacing NoSpaceAfterComma:
        enabled: false
      PSR2 ControlStructures ElseIfDeclaration NotAllowed:
        enabled: false
      Generic WhiteSpace ScopeIndent Incorrect:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - php
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false
  phan:
    enabled: true
    config:
      file_extensions: "php"
    checks:
      PhanUndeclaredVariable:
        enabled: false
      PhanNonClassMethodCall:
        enabled: false
      PhanUndeclaredClassMethod:
        enabled: false
ratings:
  paths:
  - "**.php"


exclude_paths:
- helper/**/*
- js/**/*
- PHPExcel/**/*
- tests/**/*