engines:
  phpcodesniffer:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
  phpmd:
    enabled: true
  phan:
    enabled: true
    config:
      file_extensions: "php"

ratings:
  paths:
  - "**.php"


exclude_paths:
- helper/**/*
- js/**/*
- PHPExcel/**/*
- tests/**/*