engines:
  phpcodesniffer:
    enabled: true
    checks:
      Generic WhiteSpace DisallowTabIndent TabsUsed:
        enabled: false
      PSR1 Files SideEffects FoundWithSymbols:
        enabled: false
      Squiz WhiteSpace ControlStructureSpacing SpacingAfterOpen:
        enabled: false
      Generic WhiteSpace DisallowTabIndent NonIndentTabsUsed:
        enabled: false
      Generic Formatting DisallowMultipleStatements SameLine:
        enabled: false
      Generic PHP LowerCaseConstant Found:
        enabled: false
      Squiz WhiteSpace ControlStructureSpacing SpacingBeforeClose:
        enabled: false
      Generic PHP LowerCaseKeyword Found:
        enabled: false
      Generic Files LineLength TooLong:
        enabled: false
      Generic ControlStructures InlineControlStructure NotAllowed:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - php
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false
  phan:
    enabled: true
    config:
      file_extensions: "php"

ratings:
  paths:
  - "**.php"


exclude_paths:
- helper/**/*
- js/**/*
- PHPExcel/**/*
- tests/**/*